[toolchain]
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
diggo_protocol = "H3Y8GgTnvwv5U1bajfzj386YSPC48vvwjFroXYyHZFj5"

[programs.devnet]
diggo_protocol = "H3Y8GgTnvwv5U1bajfzj386YSPC48vvwjFroXYyHZFj5"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"
