[toolchain]
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
diggo_protocol = "BLF7g1SbT72xb5M8rVrD7V3mdDXxb1AqwChcoeF4ppmE"

[programs.devnet]
diggo_protocol = "BLF7g1SbT72xb5M8rVrD7V3mdDXxb1AqwChcoeF4ppmE"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"
