//! Golden vectors for the TypeScript mirrors (WS-G).
//!
//! Design 8.4 makes the chain authoritative: Rust generates the vectors, TypeScript asserts them,
//! and where the two disagree the Rust value wins because the chain is what pays. This file is the
//! Rust half. It writes tests/vectors/*.json, and when it is not asked to write it verifies that
//! what is committed is still what the program produces - so a change to a seed, a size, an error
//! code or the derivation fails here as well as in the TypeScript suite.
//!
//!   DIGGO_WRITE_VECTORS=1 cargo test -p diggo-protocol --test vectors   # regenerate
//!   cargo test -p diggo-protocol --test vectors                        # verify
//!
//! Three files are generated today. contract.json and epoch_seed.json come from the program crate
//! itself, so they are chain truth. tranche.json is the frozen starter-tranche rule expressed as an
//! independent integer implementation: it pins the simulator's model against the rule in
//! CONTRACTS.md's amendment while math/index.rs (WS-C) is still being written, and it is regenerated
//! from that file once it lands.

mod common;

use common::*;
use sha2::{Digest, Sha256};
use solana_address::Address;
use std::fs;
use std::path::PathBuf;

fn worktree_root() -> PathBuf {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.pop();
    path.pop();
    path
}

fn vectors_dir() -> PathBuf {
    worktree_root().join("tests").join("vectors")
}

fn parity_dir() -> PathBuf {
    worktree_root().join("shared").join("parity")
}

/// The header every generated TypeScript vector module carries, so nobody edits one by hand.
const TS_HEADER: &str = "/* eslint-disable */\n// GENERATED by programs/diggo-protocol/tests/vectors.rs. Do not edit.\n// Regenerate with: DIGGO_WRITE_VECTORS=1 cargo test -p diggo-protocol --test vectors\n// Source of truth: the diggo_protocol crate itself (design 8.4: the chain is authoritative).\n\n";

/// Commits one vector family: the JSON a human reads and a tool consumes, and the TypeScript module
/// the parity harness imports. The harness has to import it rather than read the file, because
/// shared/** is type-checked by the worker project, which carries no @types/node and therefore has
/// no filesystem types - and a harness that cannot be type-checked is a harness nobody runs.
fn commit_family(json_name: &str, body: String, ts_name: &str, ts_export: &str) {
    let ts = format!("{TS_HEADER}export const {ts_export} = {body};\n");
    commit(json_name, format!("{body}\n"));
    commit_at(&parity_dir().join(ts_name), ts);
}

fn commit_at(path: &std::path::Path, contents: String) {
    if std::env::var("DIGGO_WRITE_VECTORS").is_ok() {
        fs::create_dir_all(path.parent().expect("parent")).expect("vectors dir");
        fs::write(path, &contents).expect("write vector file");
        println!("wrote {}", path.display());
        return;
    }
    let committed = fs::read_to_string(path).unwrap_or_else(|error| {
        panic!(
            "{} is missing or unreadable ({error}); regenerate with DIGGO_WRITE_VECTORS=1",
            path.display()
        )
    });
    assert_eq!(
        committed, contents,
        "{} is stale: the program no longer produces these vectors",
        path.display()
    );
}

/// Writes the file when DIGGO_WRITE_VECTORS is set, and otherwise requires it to be unchanged.
fn commit(name: &str, generated: String) {
    commit_at(&vectors_dir().join(name), generated);
}

fn hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

fn json_string_array(values: &[String]) -> String {
    let quoted: Vec<String> = values.iter().map(|value| format!("\"{value}\"")).collect();
    format!("[{}]", quoted.join(", "))
}

/// The whole frozen surface: account sizes and their rent, the error codes in order, every
/// instruction's discriminator, the constants the economic decisions rest on, and the address
/// every seed list derives to for one fixed set of inputs.
#[test]
fn contract_vectors_match_the_program() {
    let creator = address("9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM");
    let owner = address("3h1zGmCwsRJnVk5BuRNMLsPaQu1y2aqXqXDWYCgrp5UG");
    let mint = mint_pda(&creator, 7);
    let coin = coin_pda(&mint);
    let vault = sponsor_vault_pda(&owner);
    let event = sponsor_event_pda(&vault, 3);

    let env = Env::new();
    let rent = |size: usize| env.svm.minimum_balance_for_rent_exemption(size);

    let accounts: Vec<String> = [
        ("ProtocolConfig", diggo_protocol::ProtocolConfig::SIZE),
        ("CurveTable", diggo_protocol::CurveTable::SIZE),
        ("Coin", diggo_protocol::Coin::SIZE),
        ("CoinVault", diggo_protocol::TOKEN_ACCOUNT_SIZE),
        ("PlayerAccount", diggo_protocol::PlayerAccount::SIZE),
        ("MiningPosition", diggo_protocol::MiningPosition::SIZE),
        ("LiquidityPool", diggo_protocol::LiquidityPool::SIZE),
        ("PoolTokenVault", diggo_protocol::TOKEN_ACCOUNT_SIZE),
        (
            "DiscoveryOpportunity",
            diggo_protocol::DiscoveryOpportunity::SIZE,
        ),
        ("GlobalBudget", diggo_protocol::GlobalBudget::SIZE),
        ("SponsorVault", diggo_protocol::SponsorVault::SIZE),
        ("SponsorEvent", diggo_protocol::SponsorEvent::SIZE),
        ("SponsorGrant", diggo_protocol::SponsorGrant::SIZE),
        ("ReferralCredit", diggo_protocol::ReferralCredit::SIZE),
        ("ReferralWeek", diggo_protocol::ReferralWeek::SIZE),
        ("Mint", diggo_protocol::MINT_V2_SIZE),
        ("TokenAccount", diggo_protocol::TOKEN_ACCOUNT_SIZE),
    ]
    .iter()
    .map(|(name, size)| {
        format!(
            "{{\"name\": \"{name}\", \"size\": {size}, \"rentLamports\": {}}}",
            rent(*size)
        )
    })
    .collect();

    // The 52 v2 error codes, by name, in the order 8.2 reserves them. New variants are appended.
    let error_names = [
        "NotImplemented",
        "InvalidPauseWindow",
        "NotTimelocked",
        "ConfigOutOfBounds",
        "InvalidRarityTable",
        "InvalidCurveTable",
        "NotActivated",
        "AccrualOverflow",
        "CrewAtMaxLevel",
        "InsufficientOre",
        "StorageCapacityExceeded",
        "ReactivationTooSoon",
        "BondAlreadyPosted",
        "NoBondPosted",
        "PositionStillActive",
        "BondCooldownActive",
        "SponsorBondNotWithdrawable",
        "VaultBelowRentExempt",
        "LedgerInvariantViolated",
        "MetadataTooLong",
        "InvalidMintLayout",
        "CurveExhausted",
        "PoolNotInitialised",
        "TwapUnavailable",
        "FeeSplitOverflow",
        "CrankTipExceedsAccrual",
        "NotCoinCreator",
        "EventNotActive",
        "EventBudgetExhausted",
        "PerCoinLimitExceeded",
        "PerWalletLimitExceeded",
        "EventAlreadyClosed",
        "UnspentWithdrawalOnly",
        "InvalidEventKind",
        "EpochNotRolled",
        "SeedTargetInFuture",
        "SeedTargetNotInSysvar",
        "SeedAlreadyCommitted",
        "SeedNotCommitted",
        "CoinNotAdvanced",
        "RollAlreadyExists",
        "NotDiscoveryEligible",
        "OpportunityExpired",
        "OpportunityAlreadySettled",
        "DailyCapExceeded",
        "WeeklyCapExceeded",
        "GlobalCapExceeded",
        "EpochBudgetExhausted",
        "UnclaimedRewards",
        "BondRetired",
        "ReferralAmountOutOfRange",
        "ReferralWeeklyCapExceeded",
        "ReferralRefereeMismatch",
    ];
    let errors: Vec<String> = error_names
        .iter()
        .enumerate()
        .map(|(index, name)| {
            format!(
                "{{\"name\": \"{name}\", \"code\": {}}}",
                6048 + index
            )
        })
        .collect();

    let instruction_names = [
        "initialize_protocol",
        "update_fee_config",
        "update_discovery_limits",
        "set_rarity_table",
        "set_curve_table",
        "schedule_pause",
        "unpause",
        "launch_token",
        "buy",
        "sell",
        "pool_buy",
        "pool_sell",
        "graduate_market",
        "sweep_fees",
        "claim_creator_fees",
        "crank_tip",
        "init_sponsor_vault",
        "fund_sponsor_vault",
        "withdraw_sponsor_vault",
        "create_sponsor_event",
        "close_sponsor_event",
        "initialize_player",
        "activate",
        "collect_ore",
        "upgrade_crew",
        "assign_power",
        "remove_power",
        "switch_mine",
        "claim_rewards",
        "request_unbond",
        "withdraw_bond",
        "advance_mine",
        "commit_epoch_seed",
        "create_discovery_roll",
        "settle_discovery",
        "expire_opportunity",
        "credit_referral_ore",
    ];
    let instructions: Vec<String> = instruction_names
        .iter()
        .map(|name| {
            format!(
                "{{\"name\": \"{name}\", \"discriminatorHex\": \"{}\"}}",
                hex(&discriminator(name))
            )
        })
        .collect();

    let pda = |name: &str, seeds: &[&str], address: Address| {
        format!(
            "{{\"name\": \"{name}\", \"seeds\": {}, \"address\": \"{address}\"}}",
            json_string_array(&seeds.iter().map(|seed| seed.to_string()).collect::<Vec<_>>())
        )
    };
    let pdas: Vec<String> = vec![
        pda("protocol", &["protocol"], protocol_pda()),
        pda("treasury", &["treasury"], treasury_pda()),
        pda("crankPool", &["crank-pool"], crank_pool_pda()),
        pda("curveTable", &["curve-table"], curve_table_pda()),
        pda("mint", &["mint", "creator", "nonce:u8"], mint),
        pda("coin", &["coin", "mint"], coin),
        pda("coinVault", &["vault", "mint"], vault_pda(&mint)),
        pda("pool", &["pool", "mint"], pool_pda(&mint)),
        pda("poolTokenVault", &["pool-vault", "mint"], pool_vault_pda(&mint)),
        pda("poolSolVault", &["pool-sol", "mint"], pool_sol_pda(&mint)),
        pda("player", &["player", "owner"], player_pda(&owner)),
        pda(
            "position",
            &["position", "coin", "owner"],
            position_pda(&coin, &owner),
        ),
        pda(
            "opportunity",
            &["opportunity", "coin", "owner", "windowIndex:u16le"],
            opportunity_pda(&coin, &owner, 3),
        ),
        pda(
            "globalBudget",
            &["global-budget", "dayIndex:u16le"],
            global_budget_pda(19_000),
        ),
        pda("sponsorVault", &["sponsor-vault", "sponsorOwner"], vault),
        pda(
            "sponsorEvent",
            &["sponsor-event", "sponsorVault", "eventId:u32le"],
            event,
        ),
        pda(
            "sponsorGrant",
            &["sponsor-grant", "sponsorEvent", "subject"],
            sponsor_grant_pda(&event, &coin),
        ),
        pda(
            "referralCredit",
            &["referral", "referrer", "referee"],
            referral_credit_pda(&owner, &creator),
        ),
        pda("referralWeek", &["referral_week", "referrer"], referral_week_pda(&owner)),
    ];

    let constants: Vec<String> = vec![
        ("bondLamports", diggo_protocol::BOND_LAMPORTS as u128),
        ("bondCooldownSeconds", diggo_protocol::BOND_COOLDOWN_SECONDS as u128),
        ("starterEfficiencyBps", diggo_protocol::STARTER_EFFICIENCY_BPS as u128),
        ("starterTrancheBps", diggo_protocol::STARTER_TRANCHE_BPS as u128),
        ("epochSeedDelaySlots", diggo_protocol::EPOCH_SEED_DELAY_SLOTS as u128),
        (
            "epochSeedMaxLatenessSlots",
            diggo_protocol::EPOCH_SEED_MAX_LATENESS_SLOTS as u128,
        ),
        ("slotHashesWindow", diggo_protocol::SLOT_HASHES_WINDOW as u128),
        ("crankTipBps", diggo_protocol::CRANK_TIP_BPS as u128),
        ("maxPauseSeconds", diggo_protocol::MAX_PAUSE_SECONDS as u128),
        ("maxRarityTiers", diggo_protocol::MAX_RARITY_TIERS as u128),
        ("crewComponents", diggo_protocol::CREW_COMPONENTS as u128),
        ("maxCrewLevel", diggo_protocol::MAX_CREW_LEVEL as u128),
        ("minCurveMiningBlocks", diggo_protocol::MIN_CURVE_MINING_BLOCKS as u128),
        ("bps", diggo_protocol::BPS),
        ("indexScale", diggo_protocol::INDEX_SCALE),
        ("maxReferralOrePerCredit", diggo_protocol::MAX_REFERRAL_ORE_PER_CREDIT as u128),
        ("maxReferralOreCreditsPerWeek", diggo_protocol::MAX_REFERRAL_ORE_CREDITS_PER_WEEK as u128),
        (
            "discoveryDailyCapLamports",
            diggo_protocol::DEFAULT_DISCOVERY_DAILY_CAP_LAMPORTS as u128,
        ),
        (
            "discoveryWeeklyCapLamports",
            diggo_protocol::DEFAULT_DISCOVERY_WEEKLY_CAP_LAMPORTS as u128,
        ),
        (
            "discoveryGlobalDailyCapLamports",
            diggo_protocol::DEFAULT_DISCOVERY_GLOBAL_DAILY_CAP_LAMPORTS as u128,
        ),
        (
            "discoveryEpochBudgetLamports",
            diggo_protocol::DEFAULT_DISCOVERY_EPOCH_BUDGET_LAMPORTS as u128,
        ),
    ]
    .iter()
    .map(|(name, value)| format!("{{\"name\": \"{name}\", \"value\": {value}}}"))
    .collect();

    let body = format!(
        "{{\n  \"programId\": \"{}\",\n  \"accounts\": [\n    {}\n  ],\n  \"errors\": [\n    {}\n  ],\n  \"instructions\": [\n    {}\n  ],\n  \"constants\": [\n    {}\n  ],\n  \"pdas\": [\n    {}\n  ]\n}}",
        PROGRAM_ID_STR,
        accounts.join(",\n    "),
        errors.join(",\n    "),
        instructions.join(",\n    "),
        constants.join(",\n    "),
        pdas.join(",\n    "),
    );
    commit_family(
        "contract.json",
        body,
        "vectors.contract.generated.ts",
        "CONTRACT",
    );
}

/// The epoch-seed derivation of design 4.1: sha256(epoch_seed || owner || window_index as u16 LE).
/// This half is frozen - the expansion into occur, rarity and amount is WS-C's to write, and its
/// vectors belong beside these once math/index.rs and instructions/discovery.rs land.
#[test]
fn epoch_seed_vectors_match_the_derivation() {
    let cases: Vec<String> = (0..8)
        .map(|index| {
            let mut seed = [0u8; 32];
            for (position, byte) in seed.iter_mut().enumerate() {
                *byte = (index * 31 + position) as u8;
            }
            let mut owner = [0u8; 32];
            for (position, byte) in owner.iter_mut().enumerate() {
                *byte = (200 + index * 7 + position) as u8;
            }
            let window = (index * 3) as u16;
            let mut hasher = Sha256::new();
            hasher.update(seed);
            hasher.update(owner);
            hasher.update(window.to_le_bytes());
            let digest = hasher.finalize();
            format!(
                "{{\"epochSeedHex\": \"{}\", \"ownerHex\": \"{}\", \"windowIndex\": {}, \"digestHex\": \"{}\"}}",
                hex(&seed),
                hex(&owner),
                window,
                hex(&digest)
            )
        })
        .collect();
    let body = format!(
        "{{\n  \"derivation\": \"sha256(epoch_seed || owner || window_index_u16_le)\",\n  \"cases\": [\n    {}\n  ]\n}}",
        cases.join(",\n    ")
    );
    commit_family(
        "epoch_seed.json",
        body,
        "vectors.epochSeed.generated.ts",
        "EPOCH_SEED",
    );
}

/// The starter-tranche amendment of CONTRACTS.md, as integer arithmetic:
///
///   starter_take = min(block * STARTER_TRANCHE_BPS / BPS, block * starter_power / total_power)
///   bonded_take  = block - starter_take when there is bonded power, else 0
///   remainder    = block - starter_take - bonded_take, which stays in the Mining Reserve
///
/// The simulator (scripts/sim/v2rules.ts) asserts these same vectors, so its model cannot drift
/// from the rule the chain enforces. WS-C's math/index.rs is the other half of this pair.
#[test]
fn tranche_vectors_match_the_amendment() {
    let cases: Vec<String> = [
        (10_000u64, 0u64, 0u64),
        (10_000, 0, 1_000),
        (10_000, 1_000, 0),
        (10_000, 1_000, 1_000),
        (10_000, 1_000, 100_000),
        (10_000, 9_000, 1_000),
        (7_500, 1_400, 900),
        (1, 0, 1),
        (3, 1, 1),
        (999, 1, 1),
        (1_000_000, 1, 999_999),
        (7, 0, 5),
    ]
    .iter()
    .map(|(block, bonded, starter)| {
        let block = *block;
        let bonded = *bonded;
        let starter = *starter;
        let total = bonded + starter;
        let (starter_take, bonded_take) = if total == 0 {
            (0, 0)
        } else {
            let pro_rata = (block as u128 * starter as u128 / total as u128) as u64;
            let cap = (block as u128 * diggo_protocol::STARTER_TRANCHE_BPS as u128
                / diggo_protocol::BPS) as u64;
            let take = pro_rata.min(cap);
            if bonded == 0 {
                (take, 0)
            } else {
                (take, block - take)
            }
        };
        let remainder = block - starter_take - bonded_take;
        format!(
            "{{\"blockReward\": {block}, \"bondedPower\": {bonded}, \"starterPower\": {starter}, \"starterTake\": {starter_take}, \"bondedTake\": {bonded_take}, \"remainder\": {remainder}}}"
        )
    })
    .collect();
    let body = format!(
        "{{\n  \"rule\": \"starter tranche cap, CONTRACTS.md amendment\",\n  \"cases\": [\n    {}\n  ]\n}}",
        cases.join(",\n    ")
    );
    commit_family(
        "tranche.json",
        body,
        "vectors.tranche.generated.ts",
        "TRANCHE",
    );
}
