//! math::power.rs - derived Mining Power. WS-A owns this file.
//!
//! Two things live here and nowhere else:
//!
//! 1. The **frozen curve tables** (design section 7). `crewPower()` is `pow(x, 0.62)` and
//!    `1 + gain * (1 - e^-k)` off-chain, and emulating those in integer math would drift from
//!    the values the client already publishes. Instead the numbers ship as program constant
//!    data: zero compute units to read, no rounding questions, and a golden-vector test that
//!    pins them against `shared/crew.ts` (shared/parity/player.json) so the two cannot
//!    silently diverge.
//! 2. **Derived power.** `assign_power` takes no power argument: a position's power is
//!    `mining_power(crew_levels, maturity)` computed in-program, so no caller can assert
//!    it, no keeper can push it, and nothing off-chain decides it. Money cannot reach it: the
//!    only input a player controls is `crew_levels`, and the only way to raise those is
//!    `upgrade_crew`, which is paid in ORE, and ORE is only ever earned by playing.

use crate::*;

// `math/mod.rs` is read-only in Phase 1 (CONTRACTS.md rule 1), so the new `math/ore.rs` this
// workstream owns is declared here with an explicit path instead of there. The integrator
// should move these two lines into `math/mod.rs` and delete them from this file.
#[path = "ore.rs"]
pub mod ore;
pub use ore::*;

/// Bounded keeper power rule: never above ProtocolConfigV4.max_crew_power (itself clamped
/// by MAX_CREW_POWER_HARD_CAP), and never more than max_power_increase_bps plus the
/// always-allowed MIN_POWER_STEP above the previous value. Decreases are intentionally
/// unbounded so abuse handling can still reduce a player's power.
pub fn validate_power_update(
    protocol: &ProtocolConfigV4,
    previous_power: u64,
    new_power: u64,
) -> Result<()> {
    require!(
        new_power <= protocol.max_crew_power && new_power <= MAX_CREW_POWER_HARD_CAP,
        DiggoError::PowerOutOfRange
    );
    let allowed = previous_power
        .saturating_add(mul_bps(previous_power, protocol.max_power_increase_bps)?)
        .saturating_add(MIN_POWER_STEP);
    require!(new_power <= allowed, DiggoError::PowerIncreaseTooLarge);
    Ok(())
}

// ---- v2: the maturity ramp, the curve tables and the derived power -------------------------

/// Slots in one day at Solana's 400 ms target slot time. Power maturity is measured from the
/// PlayerAccount's creation **slot** (design section 5), because a slot is not something a
/// validator can nudge for profit the way it can nudge a timestamp. ORE maturity uses
/// `created_at` instead, where the extra precision is worth more than the residual.
pub const SLOTS_PER_DAY: u64 = 216_000;

/// Every crew branch starts at level 1 and no branch may pass MAX_CREW_LEVEL.
pub const CREW_START_LEVEL: u16 = 1;

/// Branch order, as the design names it: miners, drills, carts, foreman, storage. The
/// Foreman is the branch whose level discounts every other branch's upgrade price.
pub const CREW_MINERS_INDEX: usize = 0;
pub const CREW_DRILLS_INDEX: usize = 1;
pub const CREW_CARTS_INDEX: usize = 2;
pub const CREW_FOREMAN_INDEX: usize = 3;
pub const CREW_STORAGE_INDEX: usize = 4;

/// The maturity ramp as the (day, bps) schedule of design section 5: day 1 20%, day 3 40%,
/// day 7 70%, then 100%. A farm's wallets have to age before they bring a full share, and
/// nothing about that is a paywall. Power and ORE use the same schedule.
pub fn maturity_ramp_bps(days: u64) -> u16 {
    for (up_to_day, bps) in MATURITY_RAMP {
        if days < up_to_day {
            return bps;
        }
    }
    BPS as u16
}

/// Maturity of a PlayerAccount measured from its creation slot, in bps of full power.
pub fn power_maturity_bps(created_slot: u64, now_slot: u64) -> u16 {
    if now_slot < created_slot {
        return 0;
    }
    maturity_ramp_bps((now_slot - created_slot) / SLOTS_PER_DAY)
}

/// Table index of a crew level, or ConfigOutOfBounds when a caller hands over a level the
/// tables do not cover. Levels are only ever written by `upgrade_crew`, which refuses to pass
/// MAX_CREW_LEVEL, so this is a defensive bound rather than a reachable state.
pub fn level_index(level: u16) -> Result<usize> {
    require!(
        level >= CREW_START_LEVEL && level <= MAX_CREW_LEVEL,
        DiggoError::ConfigOutOfBounds
    );
    Ok((level - CREW_START_LEVEL) as usize)
}

// ---- frozen curve tables (generated by scripts/tmp/A/gen-curves.mjs) ----
// One entry per crew level 1..=MAX_CREW_LEVEL. Rounded once, from the same
// double-precision formulas shared/crew.ts and shared/ore.ts publish.

/// floor(starter_power * level ^ miner_power_exponent): the Miners branch's base power.
pub static MINERS_POWER: [u32; CURVE_TABLE_POWER_LEN] = [
      100,   153,   197,   236,   271,   303,   334,   363,   390,   416,
      442,   466,   490,   513,   536,   557,   579,   600,   620,   640,
      660,   679,   698,   717,   735,   753,   771,   789,   806,   823,
      840,   857,   873,   890,   906,   922,   938,   953,   969,   984,
      999,  1014,  1029,  1044,  1059,  1073,  1088,  1102,  1116,  1130,
     1144,  1158,  1172,  1185,  1199,  1213,  1226,  1239,  1252,  1266,
     1279,  1292,  1304,  1317,  1330,  1343,  1355,  1368,  1380,  1393,
     1405,  1417,  1429,  1441,  1453,  1465,  1477,  1489,  1501,  1513,
     1524,  1536,  1548,  1559,  1571,  1582,  1594,  1605,  1616,  1627,
     1639,  1650,  1661,  1672,  1683,  1694,  1705,  1716,  1727,  1737,
];

/// round(10_000 * drill_efficiency(level)): Drills multiply Miner output, never add power.
pub static DRILL_EFFICIENCY_BPS: [u16; CURVE_TABLE_POWER_LEN] = [
     10000,  10240,  10461,  10664,  10850,  11022,  11180,  11326,  11460,  11583,
     11696,  11800,  11896,  11985,  12066,  12140,  12209,  12272,  12331,  12384,
     12433,  12479,  12520,  12559,  12594,  12626,  12656,  12684,  12709,  12732,
     12754,  12773,  12792,  12808,  12824,  12838,  12851,  12863,  12874,  12884,
     12893,  12902,  12909,  12917,  12923,  12929,  12935,  12940,  12945,  12949,
     12953,  12957,  12961,  12964,  12967,  12969,  12972,  12974,  12976,  12978,
     12980,  12981,  12983,  12984,  12986,  12987,  12988,  12989,  12990,  12990,
     12991,  12992,  12993,  12993,  12994,  12994,  12995,  12995,  12995,  12996,
     12996,  12996,  12997,  12997,  12997,  12997,  12998,  12998,  12998,  12998,
     12998,  12998,  12999,  12999,  12999,  12999,  12999,  12999,  12999,  12999,
];

/// round(10_000 * max(minimum_multiplier, 2 - foreman_discount(level))).
pub static FOREMAN_COST_BPS: [u16; CURVE_TABLE_POWER_LEN] = [
     10000,   9807,   9626,   9456,   9298,   9150,   9011,   8881,   8760,   8646,
      8540,   8441,   8348,   8261,   8180,   8104,   8032,   7966,   7904,   7845,
      7791,   7740,   7692,   7647,   7606,   7567,   7530,   7496,   7464,   7434,
      7406,   7380,   7355,   7332,   7311,   7291,   7272,   7255,   7238,   7223,
      7208,   7195,   7182,   7171,   7160,   7149,   7140,   7131,   7122,   7114,
      7107,   7100,   7094,   7088,   7082,   7077,   7072,   7067,   7063,   7059,
      7055,   7051,   7048,   7045,   7042,   7039,   7037,   7034,   7032,   7030,
      7028,   7026,   7025,   7023,   7022,   7020,   7019,   7018,   7017,   7015,
      7014,   7014,   7013,   7012,   7011,   7010,   7010,   7009,   7008,   7008,
      7007,   7007,   7007,   7006,   7006,   7005,   7005,   7005,   7004,   7004,
];

/// `floor(miners_power[miners] * drill_bps[drills] / BPS)`: the crew's raw Mining Power.
///
/// Drills multiply Miner output rather than adding a second flat term, and no other branch
/// contributes power at all - Carts and Foreman raise ORE and cut prices, Storage raises
/// capacity. That is what keeps the branches strategically separate, and it is why a crew
/// that upgrades Carts does not mine harder.
pub fn crew_power(levels: [u16; CREW_COMPONENTS]) -> Result<u64> {
    let miners = MINERS_POWER[level_index(levels[0])?] as u64;
    let drills = DRILL_EFFICIENCY_BPS[level_index(levels[1])?] as u64;
    u64::try_from(
        (miners as u128)
            .checked_mul(drills as u128)
            .ok_or(DiggoError::MathOverflow)?
            / BPS,
    )
    .map_err(|_| error!(DiggoError::MathOverflow))
}

/// `floor(upgrade_cost[component][level - 1] * foreman_cost_bps[foreman] / BPS)`: the ORE
/// price of taking `component` from `level` to `level + 1`.
///
/// The Foreman branch discounts the price, which is why the discount is applied here rather
/// than baked into the table: one table then serves every Foreman level, and the discount can
/// never be steered by whoever is buying.
pub fn upgrade_ore_cost(component: u8, level: u16, foreman_level: u16) -> Result<u64> {
    require!(
        (component as usize) < CREW_COMPONENTS,
        DiggoError::ConfigOutOfBounds
    );
    let base = UPGRADE_ORE_COST[component as usize][level_index(level)?] as u64;
    let discount = FOREMAN_COST_BPS[level_index(foreman_level)?] as u64;
    u64::try_from(
        (base as u128)
            .checked_mul(discount as u128)
            .ok_or(DiggoError::MathOverflow)?
            / BPS,
    )
    .map_err(|_| error!(DiggoError::MathOverflow))
}

/// The power a position is armed with: the crew's raw power, throttled by account maturity and
/// by nothing else.
///
/// The starter penalty is retired. An unbonded wallet used to bring `STARTER_EFFICIENCY_BPS` of
/// the same maturity-adjusted power and the bond bought the rest, which made a full crew worth a
/// quarter of itself to anyone who declined to park 0.07 SOL. Power is now a function of crew
/// and maturity alone: there is no deposit to post, no bond to read, and no parameter here that
/// could reintroduce a throttle. Maturity is the only one left, and it is time, not money.
pub fn mining_power(levels: [u16; CREW_COMPONENTS], maturity_bps: u16) -> Result<u64> {
    let raw = crew_power(levels)?;
    mul_bps(raw, maturity_bps)
}

// ---- the optional CurveTable override (design 7, set_curve_table) --------------------------
//
// The tables ship as constant data, and `CurveTable` is only the timelocked override for the
// day a balance pass needs new numbers. It carries a miner-power column and a full upgrade-cost
// matrix, but no drill-efficiency and no foreman-discount column, so those two stay on the
// constants whatever the override says. The gap is reported rather than papered over: see
// docs/CONTRACT_CHANGE_REQUESTS.md.

/// `floor(table.power[miners] * drill_bps[drills] / BPS)`, the override's version of
/// `crew_power`. No instruction can reach this yet, because no instruction that derives power
/// takes a `CurveTable` account - which is itself one of the reported gaps.
pub fn curve_table_crew_power(table: &CurveTable, levels: [u16; CREW_COMPONENTS]) -> Result<u64> {
    let miners = table.power[level_index(levels[CREW_MINERS_INDEX])?] as u64;
    let drills = DRILL_EFFICIENCY_BPS[level_index(levels[CREW_DRILLS_INDEX])?] as u64;
    u64::try_from(
        (miners as u128)
            .checked_mul(drills as u128)
            .ok_or(DiggoError::MathOverflow)?
            / BPS,
    )
    .map_err(|_| error!(DiggoError::MathOverflow))
}

/// `floor(table.upgrade_ore_cost[c][level - 1] * foreman_cost_bps[foreman] / BPS)`, the
/// override's version of `upgrade_ore_cost`.
pub fn curve_table_upgrade_ore_cost(
    table: &CurveTable,
    component: u8,
    level: u16,
    foreman_level: u16,
) -> Result<u64> {
    require!(
        (component as usize) < CREW_COMPONENTS,
        DiggoError::ConfigOutOfBounds
    );
    let base = table.upgrade_ore_cost[component as usize][level_index(level)?] as u64;
    let discount = FOREMAN_COST_BPS[level_index(foreman_level)?] as u64;
    u64::try_from(
        (base as u128)
            .checked_mul(discount as u128)
            .ok_or(DiggoError::MathOverflow)?
            / BPS,
    )
    .map_err(|_| error!(DiggoError::MathOverflow))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn levels(miners: u16, drills: u16) -> [u16; CREW_COMPONENTS] {
        [miners, drills, CREW_START_LEVEL, CREW_START_LEVEL, CREW_START_LEVEL]
    }

    #[test]
    fn tables_are_monotonic_and_start_at_the_starter_crew() {
        for i in 1..CURVE_TABLE_POWER_LEN {
            assert!(MINERS_POWER[i] > MINERS_POWER[i - 1]);
            assert!(UPGRADE_ORE_COST[0][i] > UPGRADE_ORE_COST[0][i - 1]);
        }
        assert_eq!(MINERS_POWER[0], 100);
        assert_eq!(DRILL_EFFICIENCY_BPS[0], 10_000);
        assert_eq!(FOREMAN_COST_BPS[0], 10_000);
        for level in 1..=MAX_CREW_LEVEL {
            assert!(DRILL_EFFICIENCY_BPS[(level - 1) as usize] >= 10_000);
            assert!(FOREMAN_COST_BPS[(level - 1) as usize] <= 10_000);
            assert!(FOREMAN_COST_BPS[(level - 1) as usize] >= 4_000);
        }
    }

    #[test]
    fn crew_power_is_monotonic_and_starts_at_one_hundred() {
        assert_eq!(crew_power(levels(1, 1)).unwrap(), 100);
        let mut previous = 0;
        for level in 1..=MAX_CREW_LEVEL {
            let power = crew_power(levels(level, 1)).unwrap();
            assert!(power > previous);
            previous = power;
            // Drills are a multiplier, so raising them never lowers power either.
            assert!(crew_power(levels(1, level)).unwrap() >= 100);
        }
    }

    #[test]
    fn crew_power_matches_the_published_curve() {
        // The values the frozen tables carry for the default config. shared/parity/player.json
        // republishes them from this side for WS-G, and shared/crew.test.ts asserts the same.
        assert_eq!(crew_power(levels(2, 1)).unwrap(), 153);
        assert_eq!(crew_power(levels(100, 1)).unwrap(), 1_737);
        assert_eq!(crew_power(levels(100, 100)).unwrap(), 2_257);
    }

    #[test]
    fn upgrade_cost_rises_with_level_and_falls_with_the_foreman() {
        assert_eq!(upgrade_ore_cost(0, 1, CREW_START_LEVEL).unwrap(), 80);
        assert!(upgrade_ore_cost(0, 1, MAX_CREW_LEVEL).unwrap() < upgrade_ore_cost(0, 1, CREW_START_LEVEL).unwrap());
        assert!(upgrade_ore_cost(0, 99, CREW_START_LEVEL).unwrap() > upgrade_ore_cost(0, 98, CREW_START_LEVEL).unwrap());
        // MAX_CREW_LEVEL itself is a real level with a real price; refusing to buy past it is
        // upgrade_crew's job (CrewAtMaxLevel), because a table with no entry would panic.
        assert!(upgrade_ore_cost(0, MAX_CREW_LEVEL, CREW_START_LEVEL).unwrap() > 0);
        assert!(upgrade_ore_cost(0, MAX_CREW_LEVEL + 1, CREW_START_LEVEL).is_err());
        assert!(upgrade_ore_cost(CREW_COMPONENTS as u8, 1, CREW_START_LEVEL).is_err());
    }

    #[test]
    fn maturity_ramp_is_the_designed_schedule() {
        assert_eq!(maturity_ramp_bps(0), 2_000);
        assert_eq!(maturity_ramp_bps(1), 4_000);
        assert_eq!(maturity_ramp_bps(2), 4_000);
        assert_eq!(maturity_ramp_bps(3), 7_000);
        assert_eq!(maturity_ramp_bps(6), 7_000);
        assert_eq!(maturity_ramp_bps(7), 10_000);
        assert_eq!(maturity_ramp_bps(10_000), 10_000);
        assert_eq!(power_maturity_bps(0, 0), 2_000);
        assert_eq!(power_maturity_bps(0, SLOTS_PER_DAY), 4_000);
        assert_eq!(power_maturity_bps(0, SLOTS_PER_DAY * 7), 10_000);
        // A clock that reads before the account existed is throttled, never credited.
        assert_eq!(power_maturity_bps(500, 100), 0);
    }

    #[test]
    fn power_is_crew_and_maturity_and_nothing_else() {
        let full = mining_power(levels(50, 50), 10_000).unwrap();
        assert_eq!(full, crew_power(levels(50, 50)).unwrap());
        // The retired starter efficiency cannot be reached from the derivation: the same crew at
        // full maturity is worth the whole table value, never the quarter it used to be worth to
        // an unbonded wallet.
        assert_ne!(full, full * STARTER_EFFICIENCY_BPS as u64 / BPS as u64);
        // Maturity is the only throttle left, it applies to the whole power, and nothing buys it
        // back.
        let young = mining_power(levels(50, 50), 2_000).unwrap();
        assert_eq!(young, full * 2_000 / 10_000);
        assert!(young < full);
    }

    #[test]
    fn mining_power_refuses_a_level_outside_the_tables() {
        assert!(mining_power(levels(0, 1), 10_000).is_err());
        assert!(mining_power(levels(MAX_CREW_LEVEL + 1, 1), 10_000).is_err());
        assert!(crew_power(levels(1, MAX_CREW_LEVEL + 1)).is_err());
    }
    // ---- golden vectors for shared/parity/player.json (WS-G) -------------------------------
    //
    // The chain is authoritative and the TypeScript is the mirror, so the vectors are emitted
    // from here and asserted there. Run with:
    //
    //   DIGGO_EMIT_PARITY=<path> cargo test --lib emit_parity_vectors

    fn push_list(out: &mut String, values: impl Iterator<Item = String>) {
        out.push('[');
        for (index, value) in values.enumerate() {
            if index > 0 {
                out.push(',');
            }
            out.push_str(&value);
        }
        out.push(']');
    }

    fn levels_str(levels: [u16; CREW_COMPONENTS]) -> String {
        format!(
            "[{},{},{},{},{}]",
            levels[0], levels[1], levels[2], levels[3], levels[4]
        )
    }

    #[test]
    fn emit_parity_vectors() {
        let Ok(target) = std::env::var("DIGGO_EMIT_PARITY") else {
            return;
        };
        let starter = [CREW_START_LEVEL; CREW_COMPONENTS];
        let maxed = [MAX_CREW_LEVEL; CREW_COMPONENTS];
        let mut out = String::new();
        out.push_str("{\n");
        out.push_str("  \"source\": \"programs/diggo-protocol (WS-A), emitted by cargo test emit_parity_vectors\",\n");
        out.push_str("  \"note\": \"The chain is authoritative: where this file and shared/*.ts disagree, this one wins and the TypeScript is the bug.\",\n");
        out.push_str("  \"levels\": 100,\n");

        out.push_str("  \"constants\": {");
        let constants: [(&str, i64); 23] = [
            ("bps", BPS as i64),
            ("indexScale", INDEX_SCALE as i64),
            ("bondLamports", BOND_LAMPORTS as i64),
            ("bondCooldownSeconds", BOND_COOLDOWN_SECONDS),
            ("starterEfficiencyBps", STARTER_EFFICIENCY_BPS as i64),
            ("starterTrancheBps", STARTER_TRANCHE_BPS as i64),
            ("slotsPerDay", SLOTS_PER_DAY as i64),
            ("activationSeconds", ACTIVATION_SECONDS),
            ("activationGraceSeconds", ACTIVATION_GRACE_SECONDS),
            ("minReactivationSeconds", MIN_REACTIVATION_SECONDS),
            ("secondsPerHour", SECONDS_PER_HOUR as i64),
            ("secondsPerDay", SECONDS_PER_DAY),
            ("baseOrePerActiveHour", BASE_ORE_PER_ACTIVE_HOUR as i64),
            ("activationBonusOre", ACTIVATION_BONUS_ORE as i64),
            ("storageBaseCapacity", STORAGE_BASE_CAPACITY as i64),
            ("offlineHoursBase", OFFLINE_HOURS_BASE as i64),
            ("offlineHoursPerStorageLevel", OFFLINE_HOURS_PER_STORAGE_LEVEL as i64),
            ("offlineHoursCap", OFFLINE_HOURS_CAP as i64),
            ("freezeCap", FREEZE_CAP as i64),
            ("freezeEarnIntervalDays", FREEZE_EARN_INTERVAL_DAYS as i64),
            ("freezeCoveredWindows", FREEZE_COVERED_WINDOWS),
            ("crewComponents", CREW_COMPONENTS as i64),
            ("maxCrewLevel", MAX_CREW_LEVEL as i64),
        ];
        for (index, (name, value)) in constants.iter().enumerate() {
            if index > 0 {
                out.push(',');
            }
            out.push_str(&format!("\"{name}\":{value}"));
        }
        out.push_str("},\n");

        out.push_str("  \"maturityRamp\": [");
        for (index, (day, bps)) in MATURITY_RAMP.iter().enumerate() {
            if index > 0 {
                out.push(',');
            }
            out.push_str(&format!("{{\"upToDay\":{day},\"bps\":{bps}}}"));
        }
        out.push_str("],\n");

        out.push_str("  \"streakMilestones\": [");
        for (index, (day, ore, freezes)) in STREAK_MILESTONES.iter().enumerate() {
            if index > 0 {
                out.push(',');
            }
            out.push_str(&format!("{{\"day\":{day},\"ore\":{ore},\"freezes\":{freezes}}}"));
        }
        out.push_str("],\n");

        out.push_str("  \"tables\": {");
        out.push_str("\"minersPower\":");
        push_list(&mut out, MINERS_POWER.iter().map(|value| value.to_string()));
        out.push_str(",\"drillEfficiencyBps\":");
        push_list(&mut out, DRILL_EFFICIENCY_BPS.iter().map(|value| value.to_string()));
        out.push_str(",\"foremanCostBps\":");
        push_list(&mut out, FOREMAN_COST_BPS.iter().map(|value| value.to_string()));
        out.push_str(",\"cartsOreBps\":");
        push_list(&mut out, CARTS_ORE_BPS.iter().map(|value| value.to_string()));
        out.push_str(",\"foremanOreBps\":");
        push_list(&mut out, FOREMAN_ORE_BPS.iter().map(|value| value.to_string()));
        out.push_str(",\"storageCapacity\":");
        push_list(&mut out, STORAGE_CAPACITY.iter().map(|value| value.to_string()));
        out.push_str(",\"cartsCapacity\":");
        push_list(&mut out, CARTS_CAPACITY.iter().map(|value| value.to_string()));
        out.push_str(",\"upgradeOreCost\":{");
        for (component, row) in UPGRADE_ORE_COST.iter().enumerate() {
            if component > 0 {
                out.push(',');
            }
            out.push_str(&format!("\"c{component}\":"));
            push_list(&mut out, row.iter().map(|value| value.to_string()));
        }
        out.push_str("}},\n");

        out.push_str("  \"crewPower\": [");
        for (index, input) in [
            [1u16, 1, 1, 1, 1],
            [2, 1, 1, 1, 1],
            [50, 50, 1, 1, 1],
            [100, 1, 1, 1, 1],
            [100, 100, 100, 100, 100],
            [1, 100, 1, 1, 1],
            [37, 82, 12, 64, 5],
        ]
        .iter()
        .enumerate()
        {
            if index > 0 {
                out.push(',');
            }
            out.push_str(&format!(
                "{{\"levels\":{},\"power\":{}}}",
                levels_str(*input),
                crew_power(*input).unwrap()
            ));
        }
        out.push_str("],\n");

        out.push_str("  \"upgradeOreCost\": [");
        let mut first = true;
        for component in 0..CREW_COMPONENTS as u8 {
            for level in [1u16, 2, 13, 50, 99, 100] {
                for foreman in [1u16, 12, 50, 100] {
                    if !first {
                        out.push(',');
                    }
                    first = false;
                    out.push_str(&format!(
                        "{{\"component\":{component},\"level\":{level},\"foreman\":{foreman},\"cost\":{}}}",
                        upgrade_ore_cost(component, level, foreman).unwrap()
                    ));
                }
            }
        }
        out.push_str("],\n");

        out.push_str("  \"miningPower\": [");
        let mut first = true;
        for input in [starter, [50, 50, 1, 1, 1], maxed] {
            for maturity in [2_000u16, 4_000, 7_000, 10_000] {
                // The \"bonded\" dimension is kept because the TypeScript mirror parses this
                // schema, and it now emits the same power twice: bonding no longer changes power.
                for bonded in [false, true] {
                    if !first {
                        out.push(',');
                    }
                    first = false;
                    out.push_str(&format!(
                        "{{\"levels\":{},\"maturityBps\":{maturity},\"bonded\":{bonded},\"power\":{}}}",
                        levels_str(input),
                        mining_power(input, maturity).unwrap()
                    ));
                }
            }
        }
        out.push_str("],\n");

        out.push_str("  \"powerMaturity\": [");
        let mut first = true;
        for day in 0..=9u64 {
            for offset in [0u64, 1, SLOTS_PER_DAY - 1] {
                let slot = day * SLOTS_PER_DAY + offset;
                if !first {
                    out.push(',');
                }
                first = false;
                out.push_str(&format!(
                    "{{\"createdSlot\":0,\"nowSlot\":{slot},\"bps\":{}}}",
                    power_maturity_bps(0, slot)
                ));
            }
        }
        out.push_str("],\n");

        out.push_str("  \"ore\": {");
        out.push_str("\"efficiencyBps\":");
        push_list(
            &mut out,
            [
                [1u16, 1, 1, 1, 1],
                [1, 1, 60, 1, 1],
                [1, 1, 1, 60, 1],
                [100, 100, 100, 100, 100],
                [1, 1, 3, 7, 1],
            ]
            .iter()
            .map(|input| {
                format!(
                    "{{\"levels\":{},\"bps\":{}}}",
                    levels_str(*input),
                    ore_efficiency_bps(*input).unwrap()
                )
            }),
        );
        out.push_str(",\"capacity\":");
        push_list(
            &mut out,
            [
                [1u16, 1, 1, 1, 1],
                [1, 1, 40, 1, 1],
                [1, 1, 1, 1, 40],
                [1, 1, 100, 100, 100],
                [2, 5, 9, 3, 77],
            ]
            .iter()
            .map(|input| {
                format!(
                    "{{\"levels\":{},\"capacity\":{}}}",
                    levels_str(*input),
                    ore_capacity(*input).unwrap()
                )
            }),
        );
        out.push_str(",\"offlineHours\":");
        push_list(
            &mut out,
            (1..=MAX_CREW_LEVEL)
                .step_by(9)
                .map(|level| {
                    let input = [1, 1, 1, 1, level];
                    format!(
                        "{{\"levels\":{},\"hours\":{}}}",
                        levels_str(input),
                        offline_hours(input).unwrap()
                    )
                }),
        );
        out.push_str(",\"accrual\":");
        let mut first = true;
        out.push('[');
        for seconds in [0u64, 1, 60, 3_599, 3_600, 7_200, 43_200, 86_400, 200_000] {
            for maturity in [2_000u16, 4_000, 7_000, 10_000] {
                for efficiency in [10_000u64, 12_500, 15_000, 16_900] {
                    if !first {
                        out.push(',');
                    }
                    first = false;
                    out.push_str(&format!(
                        "{{\"activeSeconds\":{seconds},\"maturityBps\":{maturity},\"efficiencyBps\":{efficiency},\"ore\":{}}}",
                        ore_for_active_seconds(seconds, maturity, efficiency).unwrap()
                    ));
                }
            }
        }
        out.push(']');
        out.push_str(",\"fromActivation\":");
        push_list(
            &mut out,
            (0..=10_000u16).step_by(1_000).map(|maturity| {
                format!(
                    "{{\"maturityBps\":{maturity},\"ore\":{}}}",
                    ore_from_activation(maturity).unwrap()
                )
            }),
        );
        out.push_str(",\"storeOre\":");
        let mut first = true;
        out.push('[');
        for capacity in [1_800u64, 2_400] {
            for balance in [0u64, 1_799, 1_800, 1_900] {
                for amount in [0u64, 10, 50, 500] {
                    let (after, stored, overflow) = store_ore(balance, amount, capacity);
                    if !first {
                        out.push(',');
                    }
                    first = false;
                    out.push_str(&format!(
                        "{{\"balance\":{balance},\"amount\":{amount},\"capacity\":{capacity},\"after\":{after},\"stored\":{stored},\"overflow\":{overflow}}}"
                    ));
                }
            }
        }
        out.push(']');
        out.push_str("},\n");

        out.push_str("  \"streak\": {");
        out.push_str("\"milestones\":");
        let mut first = true;
        out.push('[');
        for previous in [0u16, 1, 2, 6, 7, 29, 30, 99, 100, 364, 365] {
            for new in [1u16, 3, 7, 14, 30, 60, 100, 365, 400] {
                let (ore, freezes) = milestone_rewards(previous, new);
                if !first {
                    out.push(',');
                }
                first = false;
                out.push_str(&format!(
                    "{{\"previous\":{previous},\"new\":{new},\"ore\":{ore},\"freezes\":{freezes}}}"
                ));
            }
        }
        out.push(']');
        out.push_str(",\"freezesEarnedByInterval\":");
        let mut first = true;
        out.push('[');
        for previous in [0u16, 6, 7, 13, 14, 100] {
            for new in [0u16, 1, 7, 8, 21, 100] {
                if !first {
                    out.push(',');
                }
                first = false;
                out.push_str(&format!(
                    "{{\"previous\":{previous},\"new\":{new},\"freezes\":{}}}",
                    freezes_earned_by_interval(previous, new)
                ));
            }
        }
        out.push(']');
        out.push_str(",\"grantFreezes\":");
        let mut first = true;
        out.push('[');
        for current in 0..=4u8 {
            for granted in 0..=4u8 {
                let (freezes, awarded) = grant_freezes(current, granted);
                if !first {
                    out.push(',');
                }
                first = false;
                out.push_str(&format!(
                    "{{\"current\":{current},\"granted\":{granted},\"freezes\":{freezes},\"awarded\":{awarded}}}"
                ));
            }
        }
        out.push(']');
        out.push_str(",\"nextStreak\":");
        let mut first = true;
        out.push('[');
        for last in [None, Some(0i64), Some(1_000)] {
            for elapsed in [
                0i64,
                SECONDS_PER_DAY,
                SECONDS_PER_DAY + ACTIVATION_GRACE_SECONDS,
                SECONDS_PER_DAY + ACTIVATION_GRACE_SECONDS + 1,
                2 * SECONDS_PER_DAY + ACTIVATION_GRACE_SECONDS,
                2 * SECONDS_PER_DAY + ACTIVATION_GRACE_SECONDS + 1,
                3 * SECONDS_PER_DAY,
            ] {
                for freezes in [0u8, 1, 3] {
                    let now = last.unwrap_or(0) + elapsed;
                    let (streak, left, used) = next_streak(
                        last,
                        now,
                        4,
                        freezes,
                        ACTIVATION_SECONDS,
                        ACTIVATION_GRACE_SECONDS,
                        FREEZE_COVERED_WINDOWS,
                    );
                    if !first {
                        out.push(',');
                    }
                    first = false;
                    let last_str = match last {
                        Some(value) => value.to_string(),
                        None => "null".to_string(),
                    };
                    out.push_str(&format!(
                        "{{\"lastActivationAt\":{last_str},\"now\":{now},\"currentStreak\":4,\"freezes\":{freezes},\"streak\":{streak},\"freezesAfter\":{left},\"usedFreeze\":{used}}}"
                    ));
                }
            }
        }
        out.push(']');
        out.push_str("}\n");
        out.push_str("}\n");

        std::fs::write(&target, out).expect("write parity vectors");
    }

}
