/**
 * Parity harness: the TypeScript mirrors against the chain (WS-G, design 8.4).
 *
 * The vectors here are generated by the program crate itself
 * (programs/diggo-protocol/tests/vectors.rs) and committed as both JSON under tests/vectors/ and as
 * the TypeScript modules imported below. The JSON is what a human reads and what A/B/C's own
 * emitters sit beside; the generated modules are what this file imports, because shared/** is
 * type-checked by the worker project, which carries no @types/node and therefore has no filesystem
 * types - and a harness that cannot be type-checked is a harness nobody runs.
 *
 * The rule of 8.4 is one-way: where TypeScript and the chain disagree, the chain wins and the
 * TypeScript is the bug.
 *
 * The families that need a chain implementation which has not landed yet are consumed by
 * scripts/parity/parity.test.ts instead, which runs under the node project and can read
 * shared/parity/*.json directly - WS-A's crew, ORE and streak vectors are already there.
 */
import { describe, expect, it } from "vitest";
import { address, type Address } from "@solana/kit";
import {
  ACCOUNT_RENT_LAMPORTS,
  ACCOUNT_SIZE,
  DIGGO_INSTRUCTION_NAMES,
  LAUNCH_RENT_LAMPORTS,
  TOKEN_ACCOUNT_SIZE,
  instructionDiscriminator,
} from "../program";
import {
  deriveCoinPdaSync,
  deriveCoinVaultPdaSync,
  deriveCrankPoolPdaSync,
  deriveCurveTablePdaSync,
  deriveGlobalBudgetPdaSync,
  deriveMintPdaSync,
  deriveOpportunityPdaSync,
  derivePlayerPdaSync,
  derivePoolPdaSync,
  derivePoolSolVaultPdaSync,
  derivePoolTokenVaultPdaSync,
  derivePositionPdaSync,
  deriveProtocolPdaSync,
  deriveSponsorEventPdaSync,
  deriveSponsorGrantPdaSync,
  deriveSponsorVaultPdaSync,
  deriveTreasuryPdaSync,
  deriveReferralCreditPdaSync,
  deriveReferralWeekPdaSync,
} from "../pdas";
import { CONTRACT } from "./vectors.contract.generated";
import { EPOCH_SEED } from "./vectors.epochSeed.generated";

/** The program id of the frozen contract. A change here is a redeploy, and this is the tripwire. */
const PROGRAM_ADDRESS: Address = address("H3Y8GgTnvwv5U1bajfzj386YSPC48vvwjFroXYyHZFj5");

/** The fixed inputs the vector generator used, so the addresses below can be re-derived. */
const CREATOR = address("9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM");
const OWNER = address("3h1zGmCwsRJnVk5BuRNMLsPaQu1y2aqXqXDWYCgrp5UG");
const NONCE = 7;
const WINDOW_INDEX = 3;
const DAY_INDEX = 19_000;
const EVENT_ID = 3;

const MINT = deriveMintPdaSync(PROGRAM_ADDRESS, CREATOR, NONCE);
const COIN = deriveCoinPdaSync(PROGRAM_ADDRESS, MINT);
const SPONSOR_VAULT = deriveSponsorVaultPdaSync(PROGRAM_ADDRESS, OWNER);
const SPONSOR_EVENT = deriveSponsorEventPdaSync(PROGRAM_ADDRESS, SPONSOR_VAULT, EVENT_ID);

/** Vector name -> the client derivation of the same PDA with the same inputs. */
const PDAS: Readonly<Record<string, () => Address>> = {
  protocol: () => deriveProtocolPdaSync(PROGRAM_ADDRESS),
  treasury: () => deriveTreasuryPdaSync(PROGRAM_ADDRESS),
  crankPool: () => deriveCrankPoolPdaSync(PROGRAM_ADDRESS),
  curveTable: () => deriveCurveTablePdaSync(PROGRAM_ADDRESS),
  mint: () => deriveMintPdaSync(PROGRAM_ADDRESS, CREATOR, NONCE),
  coin: () => deriveCoinPdaSync(PROGRAM_ADDRESS, MINT),
  coinVault: () => deriveCoinVaultPdaSync(PROGRAM_ADDRESS, MINT),
  pool: () => derivePoolPdaSync(PROGRAM_ADDRESS, MINT),
  poolTokenVault: () => derivePoolTokenVaultPdaSync(PROGRAM_ADDRESS, MINT),
  poolSolVault: () => derivePoolSolVaultPdaSync(PROGRAM_ADDRESS, MINT),
  player: () => derivePlayerPdaSync(PROGRAM_ADDRESS, OWNER),
  position: () => derivePositionPdaSync(PROGRAM_ADDRESS, COIN, OWNER),
  opportunity: () =>
    deriveOpportunityPdaSync(PROGRAM_ADDRESS, COIN, OWNER, WINDOW_INDEX),
  globalBudget: () => deriveGlobalBudgetPdaSync(PROGRAM_ADDRESS, DAY_INDEX),
  sponsorVault: () => deriveSponsorVaultPdaSync(PROGRAM_ADDRESS, OWNER),
  sponsorEvent: () => deriveSponsorEventPdaSync(PROGRAM_ADDRESS, SPONSOR_VAULT, EVENT_ID),
  sponsorGrant: () => deriveSponsorGrantPdaSync(PROGRAM_ADDRESS, SPONSOR_EVENT, COIN),
  referralCredit: () => deriveReferralCreditPdaSync(PROGRAM_ADDRESS, OWNER, CREATOR),
  referralWeek: () => deriveReferralWeekPdaSync(PROGRAM_ADDRESS, OWNER),
};

/** Vector account name -> the client's own key for the same account. */
const ACCOUNT_KEYS: Readonly<Record<string, keyof typeof ACCOUNT_SIZE>> = {
  ProtocolConfig: "protocolConfig",
  CurveTable: "curveTable",
  Coin: "coin",
  CoinVault: "coinVault",
  PlayerAccount: "playerAccount",
  MiningPosition: "miningPosition",
  LiquidityPool: "liquidityPool",
  PoolTokenVault: "poolTokenVault",
  DiscoveryOpportunity: "discoveryOpportunity",
  GlobalBudget: "globalBudget",
  SponsorVault: "sponsorVault",
  SponsorEvent: "sponsorEvent",
  SponsorGrant: "sponsorGrant",
  ReferralCredit: "referralCredit",
  ReferralWeek: "referralWeek",
  Mint: "mint",
  TokenAccount: "tokenAccount",
};

function hex(bytes: Uint8Array): string {
  let out = "";
  for (const byte of bytes) out += byte.toString(16).padStart(2, "0");
  return out;
}

function fromHex(value: string): Uint8Array {
  const bytes = new Uint8Array(value.length / 2);
  for (let index = 0; index < bytes.length; index += 1) {
    bytes[index] = Number.parseInt(value.slice(index * 2, index * 2 + 2), 16);
  }
  return bytes;
}

function concat(parts: readonly Uint8Array[]): Uint8Array {
  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    out.set(part, offset);
    offset += part.length;
  }
  return out;
}

async function sha256(bytes: Uint8Array): Promise<Uint8Array> {
  const digest = await crypto.subtle.digest("SHA-256", bytes as unknown as ArrayBuffer);
  return new Uint8Array(digest);
}

describe("the frozen contract, as the chain reports it", () => {
  it("names the same program the client builds for", () => {
    expect(CONTRACT.programId).toBe(PROGRAM_ADDRESS);
  });

  it("agrees on every account size", () => {
    for (const account of CONTRACT.accounts) {
      const key = ACCOUNT_KEYS[account.name];
      expect(key, "no client key for " + account.name).toBeDefined();
      expect(ACCOUNT_SIZE[key], account.name).toBe(account.size);
    }
    // And the client has no account the chain does not.
    expect(Object.keys(ACCOUNT_SIZE).length).toBe(CONTRACT.accounts.length);
  });

  it("agrees on every instruction discriminator", () => {
    type InstructionName = Parameters<typeof instructionDiscriminator>[0];
    const reported = CONTRACT.instructions.map((instruction) => instruction.name);
    for (const instruction of CONTRACT.instructions) {
      const derived = instructionDiscriminator(instruction.name as InstructionName);
      expect(hex(derived), instruction.name).toBe(instruction.discriminatorHex);
    }
    // The client's table is the chain's report, exactly, in both directions: an instruction the
    // client invents, or one it drops, fails this line. There is no set of names allowed to differ
    // any more - post_bond was the last one, and regeneration removed it from the vectors, so the
    // strict comparison is the tripwire rather than an allowance with an expiry date.
    expect([...DIGGO_INSTRUCTION_NAMES].sort()).toEqual(reported.sort());
  });

  it("agrees on every PDA, byte for byte, in every seed list", () => {
    for (const pda of CONTRACT.pdas) {
      const derive = PDAS[pda.name];
      expect(derive, "no client derivation for " + pda.name).toBeDefined();
      expect(derive(), pda.name).toBe(pda.address);
    }
    expect(Object.keys(PDAS).length).toBe(CONTRACT.pdas.length);
  });
});

describe("the epoch seed derivation of design 4.1", () => {
  it("is sha256(epoch_seed || owner || window_index as u16 little-endian)", async () => {
    for (const vector of EPOCH_SEED.cases) {
      const window = new Uint8Array(2);
      new DataView(window.buffer).setUint16(0, vector.windowIndex, true);
      const digest = await sha256(
        concat([fromHex(vector.epochSeedHex), fromHex(vector.ownerHex), window]),
      );
      expect(hex(digest), "window " + String(vector.windowIndex)).toBe(vector.digestHex);
    }
  });

  it("is a pure function of the seed, the wallet and the window", async () => {
    // The property sponsorship depends on: nothing else can enter the derivation, so an event can
    // never change an outcome. Same inputs, same digest, whatever else the accounts say.
    const first = EPOCH_SEED.cases[0];
    const window = new Uint8Array([0, 0]);
    const once = await sha256(
      concat([fromHex(first.epochSeedHex), fromHex(first.ownerHex), window]),
    );
    const twice = await sha256(
      concat([fromHex(first.epochSeedHex), fromHex(first.ownerHex), window]),
    );
    expect(hex(once)).toBe(hex(twice));
    expect(hex(once)).toBe(first.digestHex);
  });
});

/**
 * The rent table is the other half of the size table: an account size nobody can price is only
 * half a contract. The chain emits both numbers in the same vector, so this asserts the client's
 * lamport table against the bank's own `minimum_balance_for_rent_exemption` rather than against a
 * second copy of the formula - arithmetic written twice can be wrong twice, and the CONTRACTS.md
 * rent column is already several hundred lamports away from the chain for five accounts.
 */
describe("the rent table, as the chain charges it", () => {
  /** Vector account name -> the client's key in ACCOUNT_RENT_LAMPORTS. */
  const RENT_KEYS: Readonly<Record<string, keyof typeof ACCOUNT_RENT_LAMPORTS>> = {
    ProtocolConfig: "protocolConfig",
    CurveTable: "curveTable",
    Coin: "coin",
    CoinVault: "coinVault",
    PlayerAccount: "playerAccount",
    MiningPosition: "miningPosition",
    LiquidityPool: "liquidityPool",
    DiscoveryOpportunity: "discoveryOpportunity",
    GlobalBudget: "globalBudget",
    SponsorVault: "sponsorVault",
    SponsorEvent: "sponsorEvent",
    SponsorGrant: "sponsorGrant",
    ReferralCredit: "referralCredit",
    ReferralWeek: "referralWeek",
    Mint: "mint",
  };

  it("agrees with the chain on every rent the client restates", () => {
    let compared = 0;
    for (const account of CONTRACT.accounts) {
      const key = RENT_KEYS[account.name];
      if (!key) continue;
      expect(ACCOUNT_RENT_LAMPORTS[key], account.name).toBe(BigInt(account.rentLamports));
      compared += 1;
    }
    // Every entry is checked, in both directions: the client prices nothing the chain does not name,
    // because a rent with no account behind it is a number nothing bounds.
    expect(compared).toBe(Object.keys(RENT_KEYS).length);
    expect(Object.keys(ACCOUNT_RENT_LAMPORTS).sort()).toEqual(Object.values(RENT_KEYS).sort());
  });

  it("gives every 165-byte token account the vault's rent, PoolTokenVault included", () => {
    const tokens = CONTRACT.accounts.filter((account) => account.size === TOKEN_ACCOUNT_SIZE);
    // CoinVault, PoolTokenVault and TokenAccount: one size, so one rent, carried once.
    expect(tokens.length).toBeGreaterThan(1);
    for (const token of tokens) {
      expect(ACCOUNT_RENT_LAMPORTS.coinVault, token.name).toBe(BigInt(token.rentLamports));
    }
  });

  it("makes a launch cost 10,098,960 lamports: the mint, the Coin and the single vault", () => {
    expect(LAUNCH_RENT_LAMPORTS).toBe(10_098_960n);
    expect(
      ACCOUNT_RENT_LAMPORTS.mint + ACCOUNT_RENT_LAMPORTS.coin + ACCOUNT_RENT_LAMPORTS.coinVault,
    ).toBe(LAUNCH_RENT_LAMPORTS);
    // Just over a hundredth of a SOL, which is the figure the launch form promises a creator.
    expect(LAUNCH_RENT_LAMPORTS).toBeLessThan(10_200_000n);
  });
});
