/* eslint-disable */
// GENERATED by programs/diggo-protocol/tests/vectors.rs. Do not edit.
// Regenerate with: DIGGO_WRITE_VECTORS=1 cargo test -p diggo-protocol --test vectors
// Source of truth: the diggo_protocol crate itself (design 8.4: the chain is authoritative).

export const EPOCH_SEED = {
  "derivation": "sha256(epoch_seed || owner || window_index_u16_le)",
  "cases": [
    {"epochSeedHex": "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f", "ownerHex": "c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7", "windowIndex": 0, "digestHex": "f34c4939e358d94861c21d8e035a6d04af1c235a7603357f4435c5587ddb6fcb"},
    {"epochSeedHex": "1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e", "ownerHex": "cfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedee", "windowIndex": 3, "digestHex": "dcfa30277253cdd6869f1aaf1b9795610cd74a71de4b47418a520f418dab6c7e"},
    {"epochSeedHex": "3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d", "ownerHex": "d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5", "windowIndex": 6, "digestHex": "8235984572c3af02834420b42f4095559a4aab97d9cdc5366508f889d6e9414e"},
    {"epochSeedHex": "5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c", "ownerHex": "dddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfc", "windowIndex": 9, "digestHex": "385147c15be8ca458ac6e18a817b118e1edcf8f96546da62ffc8a80050b7f96d"},
    {"epochSeedHex": "7c7d7e7f808182838485868788898a8b8c8d8e8f909192939495969798999a9b", "ownerHex": "e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff00010203", "windowIndex": 12, "digestHex": "dc0906b7fda9a21875c7fd2d42e04512c69b0fca7e3fef488c4c1d610a603843"},
    {"epochSeedHex": "9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9ba", "ownerHex": "ebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff000102030405060708090a", "windowIndex": 15, "digestHex": "eba94e1d2ae87f7c885ee74f654930c7bd0e6604d54fa675bbb7babbe941b76a"},
    {"epochSeedHex": "babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9", "ownerHex": "f2f3f4f5f6f7f8f9fafbfcfdfeff000102030405060708090a0b0c0d0e0f1011", "windowIndex": 18, "digestHex": "dac04667b027e318d46d3b34805557a69834875a7500e8611a4a5308698dbab1"},
    {"epochSeedHex": "d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8", "ownerHex": "f9fafbfcfdfeff000102030405060708090a0b0c0d0e0f101112131415161718", "windowIndex": 21, "digestHex": "2e092021fb19fc8bdf2cc6bca090ad027ac945470ada932cade61e685f4e46b7"}
  ]
};
